//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerApp.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CustomerApp.Resources.Language.en", typeof(Language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string trang_chu {
            get {
                return ResourceManager.GetString("trang_chu", resourceCulture);
            }
        }
        
        internal static string nhan_de_chinh_sua {
            get {
                return ResourceManager.GetString("nhan_de_chinh_sua", resourceCulture);
            }
        }
        
        internal static string gio_hang {
            get {
                return ResourceManager.GetString("gio_hang", resourceCulture);
            }
        }
        
        internal static string giao_dich {
            get {
                return ResourceManager.GetString("giao_dich", resourceCulture);
            }
        }
        
        internal static string phan_hoi {
            get {
                return ResourceManager.GetString("phan_hoi", resourceCulture);
            }
        }
        
        internal static string lich {
            get {
                return ResourceManager.GetString("lich", resourceCulture);
            }
        }
        
        internal static string tin_tuc {
            get {
                return ResourceManager.GetString("tin_tuc", resourceCulture);
            }
        }
        
        internal static string dang_xuat {
            get {
                return ResourceManager.GetString("dang_xuat", resourceCulture);
            }
        }
    }
}
