//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomerApp.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhận được mã ? Gửi lại.
        /// </summary>
        internal static string ban_chua_nhan_duoc_ma_gui_lai {
            get {
                return ResourceManager.GetString("ban_chua_nhan_duoc_ma_gui_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string btn_dong {
            get {
                return ResourceManager.GetString("btn_dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string btn_luu {
            get {
                return ResourceManager.GetString("btn_luu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string btn_xac_nhan {
            get {
                return ResourceManager.GetString("btn_xac_nhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string btn_xoa {
            get {
                return ResourceManager.GetString("btn_xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn địa chỉ.
        /// </summary>
        internal static string chon_dia_chi {
            get {
                return ResourceManager.GetString("chon_dia_chi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn diện tích sử dụng.
        /// </summary>
        internal static string chon_dien_tich_su_dung {
            get {
                return ResourceManager.GetString("chon_dien_tich_su_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn đợt mở bán.
        /// </summary>
        internal static string chon_dot_mo_ban {
            get {
                return ResourceManager.GetString("chon_dot_mo_ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn dự án.
        /// </summary>
        internal static string chon_du_an {
            get {
                return ResourceManager.GetString("chon_du_an", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn giá bán.
        /// </summary>
        internal static string chon_gia_ban {
            get {
                return ResourceManager.GetString("chon_gia_ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn giới tính.
        /// </summary>
        internal static string chon_gioi_tinh {
            get {
                return ResourceManager.GetString("chon_gioi_tinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hướng.
        /// </summary>
        internal static string chon_huong {
            get {
                return ResourceManager.GetString("chon_huong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngày sinh.
        /// </summary>
        internal static string chon_ngay_sinh {
            get {
                return ResourceManager.GetString("chon_ngay_sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn quận huyện.
        /// </summary>
        internal static string chon_quan_huyen {
            get {
                return ResourceManager.GetString("chon_quan_huyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn quốc gia.
        /// </summary>
        internal static string chon_quoc_gia {
            get {
                return ResourceManager.GetString("chon_quoc_gia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tỉnh thành.
        /// </summary>
        internal static string chon_tinh_thanh {
            get {
                return ResourceManager.GetString("chon_tinh_thanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tình trạng sản phẩm.
        /// </summary>
        internal static string chon_tinh_trang_san_pham {
            get {
                return ResourceManager.GetString("chon_tinh_trang_san_pham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chụp hình.
        /// </summary>
        internal static string chup_hinh {
            get {
                return ResourceManager.GetString("chup_hinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tỷ.
        /// </summary>
        internal static string currency_billion {
            get {
                return ResourceManager.GetString("currency_billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã bán.
        /// </summary>
        internal static string da_ban_trang_chu {
            get {
                return ResourceManager.GetString("da_ban_trang_chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra. Vui lòng thử lại sau..
        /// </summary>
        internal static string da_co_loi_xay_ra_vui_long_thu_lai_sau {
            get {
                return ResourceManager.GetString("da_co_loi_xay_ra_vui_long_thu_lai_sau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string dang_nhap {
            get {
                return ResourceManager.GetString("dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string dang_xuat {
            get {
                return ResourceManager.GetString("dang_xuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt cọc.
        /// </summary>
        internal static string dat_coc_trang_chu {
            get {
                return ResourceManager.GetString("dat_coc_trang_chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string dia_chi {
            get {
                return ResourceManager.GetString("dia_chi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diện tích sử dụng (m²).
        /// </summary>
        internal static string dien_tich_su_dung {
            get {
                return ResourceManager.GetString("dien_tich_su_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đông.
        /// </summary>
        internal static string direction_east {
            get {
                return ResourceManager.GetString("direction_east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắc.
        /// </summary>
        internal static string direction_north {
            get {
                return ResourceManager.GetString("direction_north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đông bắc.
        /// </summary>
        internal static string direction_north_east {
            get {
                return ResourceManager.GetString("direction_north_east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tây bắc.
        /// </summary>
        internal static string direction_north_west {
            get {
                return ResourceManager.GetString("direction_north_west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string direction_south {
            get {
                return ResourceManager.GetString("direction_south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đông nam.
        /// </summary>
        internal static string direction_south_east {
            get {
                return ResourceManager.GetString("direction_south_east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tây nam.
        /// </summary>
        internal static string direction_south_west {
            get {
                return ResourceManager.GetString("direction_south_west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tây.
        /// </summary>
        internal static string direction_west {
            get {
                return ResourceManager.GetString("direction_west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi Mật Khẩu.
        /// </summary>
        internal static string doi_mat_khau {
            get {
                return ResourceManager.GetString("doi_mat_khau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công..
        /// </summary>
        internal static string doi_mat_khau_thanh_cong {
            get {
                return ResourceManager.GetString("doi_mat_khau_thanh_cong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đợt mở bán.
        /// </summary>
        internal static string dot_mo_ban {
            get {
                return ResourceManager.GetString("dot_mo_ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        internal static string du_an {
            get {
                return ResourceManager.GetString("du_an", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string gender_khac {
            get {
                return ResourceManager.GetString("gender_khac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string gender_nam {
            get {
                return ResourceManager.GetString("gender_nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string gender_nu {
            get {
                return ResourceManager.GetString("gender_nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ đăng nhập.
        /// </summary>
        internal static string ghi_nho_dang_nhap {
            get {
                return ResourceManager.GetString("ghi_nho_dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán (VNĐ).
        /// </summary>
        internal static string gia_ban_vnd {
            get {
                return ResourceManager.GetString("gia_ban_vnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao Dịch.
        /// </summary>
        internal static string giao_dich {
            get {
                return ResourceManager.GetString("giao_dich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        internal static string gio_hang {
            get {
                return ResourceManager.GetString("gio_hang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string gioi_tinh {
            get {
                return ResourceManager.GetString("gioi_tinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giữ chỗ.
        /// </summary>
        internal static string giu_cho_trang_chu {
            get {
                return ResourceManager.GetString("giu_cho_trang_chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string ho_ten {
            get {
                return ResourceManager.GetString("ho_ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng.
        /// </summary>
        internal static string hop_dong_trang_chu {
            get {
                return ResourceManager.GetString("hop_dong_trang_chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng.
        /// </summary>
        internal static string huong {
            get {
                return ResourceManager.GetString("huong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng Tốt.
        /// </summary>
        internal static string huong_tot {
            get {
                return ResourceManager.GetString("huong_tot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng Xấu.
        /// </summary>
        internal static string huong_xau {
            get {
                return ResourceManager.GetString("huong_xau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string huy {
            get {
                return ResourceManager.GetString("huy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        internal static string khong_co_du_lieu {
            get {
                return ResourceManager.GetString("khong_co_du_lieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy user..
        /// </summary>
        internal static string khong_tim_thay_user {
            get {
                return ResourceManager.GetString("khong_tim_thay_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch.
        /// </summary>
        internal static string lich {
            get {
                return ResourceManager.GetString("lich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống..
        /// </summary>
        internal static string loi_he_thong {
            get {
                return ResourceManager.GetString("loi_he_thong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty.
        /// </summary>
        internal static string loyalty {
            get {
                return ResourceManager.GetString("loyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        internal static string ma_san_pham {
            get {
                return ResourceManager.GetString("ma_san_pham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực không đúng.
        /// </summary>
        internal static string ma_xac_thuc_khong_dung {
            get {
                return ResourceManager.GetString("ma_xac_thuc_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string mat_khau {
            get {
                return ResourceManager.GetString("mat_khau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        internal static string mat_khau_cu {
            get {
                return ResourceManager.GetString("mat_khau_cu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu ít nhất 6 ký tự..
        /// </summary>
        internal static string mat_khau_it_nhat_6_ky_tu {
            get {
                return ResourceManager.GetString("mat_khau_it_nhat_6_ky_tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng..
        /// </summary>
        internal static string mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("mat_khau_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống..
        /// </summary>
        internal static string mat_khau_khong_duong_de_trong {
            get {
                return ResourceManager.GetString("mat_khau_khong_duong_de_trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không khớp.
        /// </summary>
        internal static string mat_khau_khong_khop {
            get {
                return ResourceManager.GetString("mat_khau_khong_khop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string mat_khau_moi {
            get {
                return ResourceManager.GetString("mat_khau_moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm sinh âm lịch.
        /// </summary>
        internal static string nam_sinh_am_lich {
            get {
                return ResourceManager.GetString("nam_sinh_am_lich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string ngay_sinh {
            get {
                return ResourceManager.GetString("ngay_sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngũ hành.
        /// </summary>
        internal static string ngu_hanh {
            get {
                return ResourceManager.GetString("ngu_hanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn để chỉnh sửa.
        /// </summary>
        internal static string nhan_de_chinh_sua {
            get {
                return ResourceManager.GetString("nhan_de_chinh_sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập email.
        /// </summary>
        internal static string nhap_email {
            get {
                return ResourceManager.GetString("nhap_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã sản phẩm.
        /// </summary>
        internal static string nhap_ma_san_pham {
            get {
                return ResourceManager.GetString("nhap_ma_san_pham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mật khẩu cũ.
        /// </summary>
        internal static string nhap_mat_khau_cu {
            get {
                return ResourceManager.GetString("nhap_mat_khau_cu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mật khẩu mới.
        /// </summary>
        internal static string nhap_mat_khau_moi {
            get {
                return ResourceManager.GetString("nhap_mat_khau_moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số điện thoại.
        /// </summary>
        internal static string nhap_so_dien_thoai {
            get {
                return ResourceManager.GetString("nhap_so_dien_thoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số nhà/đường/phường.
        /// </summary>
        internal static string nhap_so_nha_duong_phuong {
            get {
                return ResourceManager.GetString("nhap_so_nha_duong_phuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập xác nhận mật khẩu mới.
        /// </summary>
        internal static string nhap_xac_nhan_mat_khau_moi {
            get {
                return ResourceManager.GetString("nhap_xac_nhan_mat_khau_moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang sử dụng mật khẩu cũ. Vui lòng nhập lại..
        /// </summary>
        internal static string noti_ban_dang_su_dung_mat_khau_cu_vui_long_nhap_lai {
            get {
                return ResourceManager.GetString("noti_ban_dang_su_dung_mat_khau_cu_vui_long_nhap_lai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công..
        /// </summary>
        internal static string noti_cap_nhat_thanh_cong {
            get {
                return ResourceManager.GetString("noti_cap_nhat_thanh_cong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại..
        /// </summary>
        internal static string noti_cap_nhat_that_bai {
            get {
                return ResourceManager.GetString("noti_cap_nhat_that_bai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi hình đại diện thành công..
        /// </summary>
        internal static string noti_doi_hinh_dai_dien_thanh_cong {
            get {
                return ResourceManager.GetString("noti_doi_hinh_dai_dien_thanh_cong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi hình đại diện thất bại..
        /// </summary>
        internal static string noti_doi_hinh_dai_dien_that_bai {
            get {
                return ResourceManager.GetString("noti_doi_hinh_dai_dien_that_bai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thất bại..
        /// </summary>
        internal static string noti_doi_mat_khau_that_bai {
            get {
                return ResourceManager.GetString("noti_doi_mat_khau_that_bai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng..
        /// </summary>
        internal static string noti_mat_khau_cu_khong_dung {
            get {
                return ResourceManager.GetString("noti_mat_khau_cu_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password không được chứa ký tự khoảng trắng..
        /// </summary>
        internal static string noti_mat_khau_khong_duoc_chua_ky_tu_khoan_trang {
            get {
                return ResourceManager.GetString("noti_mat_khau_khong_duoc_chua_ky_tu_khoan_trang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Dự án..
        /// </summary>
        internal static string noti_vui_long_chon_du_an {
            get {
                return ResourceManager.GetString("noti_vui_long_chon_du_an", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn giới tính..
        /// </summary>
        internal static string noti_vui_long_chon_gioi_tinh {
            get {
                return ResourceManager.GetString("noti_vui_long_chon_gioi_tinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ngày sinh..
        /// </summary>
        internal static string noti_vui_long_chon_ngay_sinh {
            get {
                return ResourceManager.GetString("noti_vui_long_chon_ngay_sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu cũ..
        /// </summary>
        internal static string noti_vui_long_nhap_mat_khau_cu {
            get {
                return ResourceManager.GetString("noti_vui_long_nhap_mat_khau_cu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu mới..
        /// </summary>
        internal static string noti_vui_long_nhap_mat_khau_moi {
            get {
                return ResourceManager.GetString("noti_vui_long_nhap_mat_khau_moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số nhà/đường/phường..
        /// </summary>
        internal static string noti_vui_long_nhap_so_nha_duong_phuong {
            get {
                return ResourceManager.GetString("noti_vui_long_nhap_so_nha_duong_phuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập xác nhận mật khẩu mới..
        /// </summary>
        internal static string noti_vui_long_nhap_xac_nhan_mat_khau_moi {
            get {
                return ResourceManager.GetString("noti_vui_long_nhap_xac_nhan_mat_khau_moi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không đúng..
        /// </summary>
        internal static string noti_xac_nhan_mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("noti_xac_nhan_mat_khau_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP được gửi về số điện thoại.
        /// </summary>
        internal static string otp_duoc_gui_ve_so_dien_thoai {
            get {
                return ResourceManager.GetString("otp_duoc_gui_ve_so_dien_thoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phản hồi.
        /// </summary>
        internal static string phan_hoi {
            get {
                return ResourceManager.GetString("phan_hoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận huyện.
        /// </summary>
        internal static string quan_huyen {
            get {
                return ResourceManager.GetString("quan_huyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quẻ mệnh.
        /// </summary>
        internal static string que_menh {
            get {
                return ResourceManager.GetString("que_menh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu ?.
        /// </summary>
        internal static string quen_mat_khau {
            get {
                return ResourceManager.GetString("quen_mat_khau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        internal static string quoc_gia {
            get {
                return ResourceManager.GetString("quoc_gia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string so_dien_thoai {
            get {
                return ResourceManager.GetString("so_dien_thoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số nhà/Đường/Phường.
        /// </summary>
        internal static string so_nha_duong_phuong {
            get {
                return ResourceManager.GetString("so_nha_duong_phuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m².
        /// </summary>
        internal static string sqm {
            get {
                return ResourceManager.GetString("sqm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trên.
        /// </summary>
        internal static string string_more_than {
            get {
                return ResourceManager.GetString("string_more_than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dưới.
        /// </summary>
        internal static string string_under {
            get {
                return ResourceManager.GetString("string_under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sự kiện.
        /// </summary>
        internal static string su_kien {
            get {
                return ResourceManager.GetString("su_kien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập/Email.
        /// </summary>
        internal static string ten_dang_nhap {
            get {
                return ResourceManager.GetString("ten_dang_nhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không đúng..
        /// </summary>
        internal static string ten_dang_nhap_khong_dung {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được để trống..
        /// </summary>
        internal static string ten_dang_nhap_khong_duoc_de_trong {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_duoc_de_trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin dự án.
        /// </summary>
        internal static string thong_tin_du_an {
            get {
                return ResourceManager.GetString("thong_tin_du_an", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư viện.
        /// </summary>
        internal static string thu_vien {
            get {
                return ResourceManager.GetString("thu_vien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string tim_kiem {
            get {
                return ResourceManager.GetString("tim_kiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        internal static string tin_tuc {
            get {
                return ResourceManager.GetString("tin_tuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh thành.
        /// </summary>
        internal static string tinh_thanh {
            get {
                return ResourceManager.GetString("tinh_thanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng sản phẩm.
        /// </summary>
        internal static string tinh_trang_san_pham {
            get {
                return ResourceManager.GetString("tinh_trang_san_pham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Bàn Phong Thủy.
        /// </summary>
        internal static string title_la_ban_phong_thuy {
            get {
                return ResourceManager.GetString("title_la_ban_phong_thuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Cá Nhân.
        /// </summary>
        internal static string title_thong_tin_ca_nhan {
            get {
                return ResourceManager.GetString("title_thong_tin_ca_nhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Gia Chủ.
        /// </summary>
        internal static string title_thong_tin_gia_chu {
            get {
                return ResourceManager.GetString("title_thong_tin_gia_chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string trang_chu {
            get {
                return ResourceManager.GetString("trang_chu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuỳ chọn.
        /// </summary>
        internal static string tuy_chon {
            get {
                return ResourceManager.GetString("tuy_chon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán đợt 1.
        /// </summary>
        internal static string unit_1st_installment_sts {
            get {
                return ResourceManager.GetString("unit_1st_installment_sts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sẵn sàng.
        /// </summary>
        internal static string unit_available_sts {
            get {
                return ResourceManager.GetString("unit_available_sts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý chuyển cọc.
        /// </summary>
        internal static string unit_collected_sts {
            get {
                return ResourceManager.GetString("unit_collected_sts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đủ tiền cọc.
        /// </summary>
        internal static string unit_deposited_sts {
            get {
                return ResourceManager.GetString("unit_deposited_sts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nháp.
        /// </summary>
        internal static string unit_draft_sts {
            get {
                return ResourceManager.GetString("unit_draft_sts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuẩn bị.
        /// </summary>
        internal static string unit_preparing_sts {
            get {
                return ResourceManager.GetString("unit_preparing_sts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giữ chỗ.
        /// </summary>
        internal static string unit_queuing_sts {
            get {
                return ResourceManager.GetString("unit_queuing_sts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt cọc.
        /// </summary>
        internal static string unit_reserve_sts {
            get {
                return ResourceManager.GetString("unit_reserve_sts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã bán.
        /// </summary>
        internal static string unit_sold_sts {
            get {
                return ResourceManager.GetString("unit_sold_sts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên không đúng..
        /// </summary>
        internal static string user_name_khong_dung {
            get {
                return ResourceManager.GetString("user_name_khong_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập họ tên hoặc email.
        /// </summary>
        internal static string vui_long_nhap_ho_ten_email {
            get {
                return ResourceManager.GetString("vui_long_nhap_ho_ten_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu.
        /// </summary>
        internal static string vui_long_nhap_mat_khau {
            get {
                return ResourceManager.GetString("vui_long_nhap_mat_khau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập OTP để xác nhận tài khoản.
        /// </summary>
        internal static string vui_long_nhap_otp_de_xac_nhan_tai_khoan {
            get {
                return ResourceManager.GetString("vui_long_nhap_otp_de_xac_nhan_tai_khoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại..
        /// </summary>
        internal static string vui_long_nhap_so_dien_thoai {
            get {
                return ResourceManager.GetString("vui_long_nhap_so_dien_thoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập xác nhận mật khẩu..
        /// </summary>
        internal static string vui_long_nhap_xac_nhan_mat_khau {
            get {
                return ResourceManager.GetString("vui_long_nhap_xac_nhan_mat_khau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string xac_nhan {
            get {
                return ResourceManager.GetString("xac_nhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mã OTP.
        /// </summary>
        internal static string xac_nhan_ma_otp {
            get {
                return ResourceManager.GetString("xac_nhan_ma_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        internal static string xac_nhan_mat_khau {
            get {
                return ResourceManager.GetString("xac_nhan_mat_khau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu mới.
        /// </summary>
        internal static string xac_nhan_mat_khau_moi {
            get {
                return ResourceManager.GetString("xac_nhan_mat_khau_moi", resourceCulture);
            }
        }
    }
}
