//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerApp.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CustomerApp.Resources.Language.en", typeof(Language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string trang_chu {
            get {
                return ResourceManager.GetString("trang_chu", resourceCulture);
            }
        }
        
        internal static string nhan_de_chinh_sua {
            get {
                return ResourceManager.GetString("nhan_de_chinh_sua", resourceCulture);
            }
        }
        
        internal static string gio_hang {
            get {
                return ResourceManager.GetString("gio_hang", resourceCulture);
            }
        }
        
        internal static string giao_dich {
            get {
                return ResourceManager.GetString("giao_dich", resourceCulture);
            }
        }
        
        internal static string phan_hoi {
            get {
                return ResourceManager.GetString("phan_hoi", resourceCulture);
            }
        }
        
        internal static string lich {
            get {
                return ResourceManager.GetString("lich", resourceCulture);
            }
        }
        
        internal static string tin_tuc {
            get {
                return ResourceManager.GetString("tin_tuc", resourceCulture);
            }
        }
        
        internal static string dang_xuat {
            get {
                return ResourceManager.GetString("dang_xuat", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap {
            get {
                return ResourceManager.GetString("ten_dang_nhap", resourceCulture);
            }
        }
        
        internal static string mat_khau {
            get {
                return ResourceManager.GetString("mat_khau", resourceCulture);
            }
        }
        
        internal static string ghi_nho_dang_nhap {
            get {
                return ResourceManager.GetString("ghi_nho_dang_nhap", resourceCulture);
            }
        }
        
        internal static string dang_nhap {
            get {
                return ResourceManager.GetString("dang_nhap", resourceCulture);
            }
        }
        
        internal static string quen_mat_khau {
            get {
                return ResourceManager.GetString("quen_mat_khau", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap_khong_duoc_de_trong {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_duoc_de_trong", resourceCulture);
            }
        }
        
        internal static string mat_khau_khong_duong_de_trong {
            get {
                return ResourceManager.GetString("mat_khau_khong_duong_de_trong", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap_khong_dung {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_dung", resourceCulture);
            }
        }
        
        internal static string khong_tim_thay_user {
            get {
                return ResourceManager.GetString("khong_tim_thay_user", resourceCulture);
            }
        }
        
        internal static string xac_nhan_ma_otp {
            get {
                return ResourceManager.GetString("xac_nhan_ma_otp", resourceCulture);
            }
        }
        
        internal static string otp_duoc_gui_ve_so_dien_thoai {
            get {
                return ResourceManager.GetString("otp_duoc_gui_ve_so_dien_thoai", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_otp_de_xac_nhan_tai_khoan {
            get {
                return ResourceManager.GetString("vui_long_nhap_otp_de_xac_nhan_tai_khoan", resourceCulture);
            }
        }
        
        internal static string huy {
            get {
                return ResourceManager.GetString("huy", resourceCulture);
            }
        }
        
        internal static string xac_nhan {
            get {
                return ResourceManager.GetString("xac_nhan", resourceCulture);
            }
        }
        
        internal static string ban_chua_nhan_duoc_ma_gui_lai {
            get {
                return ResourceManager.GetString("ban_chua_nhan_duoc_ma_gui_lai", resourceCulture);
            }
        }
        
        internal static string ma_xac_thuc_khong_dung {
            get {
                return ResourceManager.GetString("ma_xac_thuc_khong_dung", resourceCulture);
            }
        }
        
        internal static string so_dien_thoai {
            get {
                return ResourceManager.GetString("so_dien_thoai", resourceCulture);
            }
        }
        
        internal static string xac_nhan_mat_khau {
            get {
                return ResourceManager.GetString("xac_nhan_mat_khau", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_ho_ten_email {
            get {
                return ResourceManager.GetString("vui_long_nhap_ho_ten_email", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_so_dien_thoai {
            get {
                return ResourceManager.GetString("vui_long_nhap_so_dien_thoai", resourceCulture);
            }
        }
        
        internal static string user_name_khong_dung {
            get {
                return ResourceManager.GetString("user_name_khong_dung", resourceCulture);
            }
        }
        
        internal static string loi_he_thong {
            get {
                return ResourceManager.GetString("loi_he_thong", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_mat_khau {
            get {
                return ResourceManager.GetString("vui_long_nhap_mat_khau", resourceCulture);
            }
        }
        
        internal static string mat_khau_it_nhat_6_ky_tu {
            get {
                return ResourceManager.GetString("mat_khau_it_nhat_6_ky_tu", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_xac_nhan_mat_khau {
            get {
                return ResourceManager.GetString("vui_long_nhap_xac_nhan_mat_khau", resourceCulture);
            }
        }
        
        internal static string mat_khau_khong_khop {
            get {
                return ResourceManager.GetString("mat_khau_khong_khop", resourceCulture);
            }
        }
        
        internal static string doi_mat_khau_thanh_cong {
            get {
                return ResourceManager.GetString("doi_mat_khau_thanh_cong", resourceCulture);
            }
        }
        
        internal static string da_co_loi_xay_ra_vui_long_thu_lai_sau {
            get {
                return ResourceManager.GetString("da_co_loi_xay_ra_vui_long_thu_lai_sau", resourceCulture);
            }
        }
        
        internal static string mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("mat_khau_khong_dung", resourceCulture);
            }
        }
        
        internal static string giu_cho_trang_chu {
            get {
                return ResourceManager.GetString("giu_cho_trang_chu", resourceCulture);
            }
        }
        
        internal static string dat_coc_trang_chu {
            get {
                return ResourceManager.GetString("dat_coc_trang_chu", resourceCulture);
            }
        }
        
        internal static string hop_dong_trang_chu {
            get {
                return ResourceManager.GetString("hop_dong_trang_chu", resourceCulture);
            }
        }
        
        internal static string da_ban_trang_chu {
            get {
                return ResourceManager.GetString("da_ban_trang_chu", resourceCulture);
            }
        }
        
        internal static string loyalty {
            get {
                return ResourceManager.GetString("loyalty", resourceCulture);
            }
        }
    }
}
