//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerApp.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CustomerApp.Resources.Language.en", typeof(Language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string trang_chu {
            get {
                return ResourceManager.GetString("trang_chu", resourceCulture);
            }
        }
        
        internal static string nhan_de_chinh_sua {
            get {
                return ResourceManager.GetString("nhan_de_chinh_sua", resourceCulture);
            }
        }
        
        internal static string gio_hang {
            get {
                return ResourceManager.GetString("gio_hang", resourceCulture);
            }
        }
        
        internal static string giao_dich {
            get {
                return ResourceManager.GetString("giao_dich", resourceCulture);
            }
        }
        
        internal static string phan_hoi {
            get {
                return ResourceManager.GetString("phan_hoi", resourceCulture);
            }
        }
        
        internal static string lich {
            get {
                return ResourceManager.GetString("lich", resourceCulture);
            }
        }
        
        internal static string tin_tuc {
            get {
                return ResourceManager.GetString("tin_tuc", resourceCulture);
            }
        }
        
        internal static string dang_xuat {
            get {
                return ResourceManager.GetString("dang_xuat", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap {
            get {
                return ResourceManager.GetString("ten_dang_nhap", resourceCulture);
            }
        }
        
        internal static string mat_khau {
            get {
                return ResourceManager.GetString("mat_khau", resourceCulture);
            }
        }
        
        internal static string ghi_nho_dang_nhap {
            get {
                return ResourceManager.GetString("ghi_nho_dang_nhap", resourceCulture);
            }
        }
        
        internal static string dang_nhap {
            get {
                return ResourceManager.GetString("dang_nhap", resourceCulture);
            }
        }
        
        internal static string quen_mat_khau {
            get {
                return ResourceManager.GetString("quen_mat_khau", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap_khong_duoc_de_trong {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_duoc_de_trong", resourceCulture);
            }
        }
        
        internal static string mat_khau_khong_duong_de_trong {
            get {
                return ResourceManager.GetString("mat_khau_khong_duong_de_trong", resourceCulture);
            }
        }
        
        internal static string ten_dang_nhap_khong_dung {
            get {
                return ResourceManager.GetString("ten_dang_nhap_khong_dung", resourceCulture);
            }
        }
        
        internal static string khong_tim_thay_user {
            get {
                return ResourceManager.GetString("khong_tim_thay_user", resourceCulture);
            }
        }
        
        internal static string xac_nhan_ma_otp {
            get {
                return ResourceManager.GetString("xac_nhan_ma_otp", resourceCulture);
            }
        }
        
        internal static string otp_duoc_gui_ve_so_dien_thoai {
            get {
                return ResourceManager.GetString("otp_duoc_gui_ve_so_dien_thoai", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_otp_de_xac_nhan_tai_khoan {
            get {
                return ResourceManager.GetString("vui_long_nhap_otp_de_xac_nhan_tai_khoan", resourceCulture);
            }
        }
        
        internal static string huy {
            get {
                return ResourceManager.GetString("huy", resourceCulture);
            }
        }
        
        internal static string xac_nhan {
            get {
                return ResourceManager.GetString("xac_nhan", resourceCulture);
            }
        }
        
        internal static string ban_chua_nhan_duoc_ma_gui_lai {
            get {
                return ResourceManager.GetString("ban_chua_nhan_duoc_ma_gui_lai", resourceCulture);
            }
        }
        
        internal static string ma_xac_thuc_khong_dung {
            get {
                return ResourceManager.GetString("ma_xac_thuc_khong_dung", resourceCulture);
            }
        }
        
        internal static string so_dien_thoai {
            get {
                return ResourceManager.GetString("so_dien_thoai", resourceCulture);
            }
        }
        
        internal static string xac_nhan_mat_khau {
            get {
                return ResourceManager.GetString("xac_nhan_mat_khau", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_ho_ten_email {
            get {
                return ResourceManager.GetString("vui_long_nhap_ho_ten_email", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_so_dien_thoai {
            get {
                return ResourceManager.GetString("vui_long_nhap_so_dien_thoai", resourceCulture);
            }
        }
        
        internal static string user_name_khong_dung {
            get {
                return ResourceManager.GetString("user_name_khong_dung", resourceCulture);
            }
        }
        
        internal static string loi_he_thong {
            get {
                return ResourceManager.GetString("loi_he_thong", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_mat_khau {
            get {
                return ResourceManager.GetString("vui_long_nhap_mat_khau", resourceCulture);
            }
        }
        
        internal static string mat_khau_it_nhat_6_ky_tu {
            get {
                return ResourceManager.GetString("mat_khau_it_nhat_6_ky_tu", resourceCulture);
            }
        }
        
        internal static string vui_long_nhap_xac_nhan_mat_khau {
            get {
                return ResourceManager.GetString("vui_long_nhap_xac_nhan_mat_khau", resourceCulture);
            }
        }
        
        internal static string mat_khau_khong_khop {
            get {
                return ResourceManager.GetString("mat_khau_khong_khop", resourceCulture);
            }
        }
        
        internal static string doi_mat_khau_thanh_cong {
            get {
                return ResourceManager.GetString("doi_mat_khau_thanh_cong", resourceCulture);
            }
        }
        
        internal static string da_co_loi_xay_ra_vui_long_thu_lai_sau {
            get {
                return ResourceManager.GetString("da_co_loi_xay_ra_vui_long_thu_lai_sau", resourceCulture);
            }
        }
        
        internal static string btn_dong {
            get {
                return ResourceManager.GetString("btn_dong", resourceCulture);
            }
        }
        
        internal static string btn_luu {
            get {
                return ResourceManager.GetString("btn_luu", resourceCulture);
            }
        }
        
        internal static string btn_xac_nhan {
            get {
                return ResourceManager.GetString("btn_xac_nhan", resourceCulture);
            }
        }
        
        internal static string chon_ngay_sinh {
            get {
                return ResourceManager.GetString("chon_ngay_sinh", resourceCulture);
            }
        }
        
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        internal static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        internal static string gender_khac {
            get {
                return ResourceManager.GetString("gender_khac", resourceCulture);
            }
        }
        
        internal static string gender_nam {
            get {
                return ResourceManager.GetString("gender_nam", resourceCulture);
            }
        }
        
        internal static string gender_nu {
            get {
                return ResourceManager.GetString("gender_nu", resourceCulture);
            }
        }
        
        internal static string ho_ten {
            get {
                return ResourceManager.GetString("ho_ten", resourceCulture);
            }
        }
        
        internal static string ngay_sinh {
            get {
                return ResourceManager.GetString("ngay_sinh", resourceCulture);
            }
        }
        
        internal static string nhap_email {
            get {
                return ResourceManager.GetString("nhap_email", resourceCulture);
            }
        }
        
        internal static string nhap_so_dien_thoai {
            get {
                return ResourceManager.GetString("nhap_so_dien_thoai", resourceCulture);
            }
        }
        
        internal static string title_thong_tin_ca_nhan {
            get {
                return ResourceManager.GetString("title_thong_tin_ca_nhan", resourceCulture);
            }
        }
        
        internal static string chon_dia_chi {
            get {
                return ResourceManager.GetString("chon_dia_chi", resourceCulture);
            }
        }
        
        internal static string chon_gioi_tinh {
            get {
                return ResourceManager.GetString("chon_gioi_tinh", resourceCulture);
            }
        }
        
        internal static string chon_quan_huyen {
            get {
                return ResourceManager.GetString("chon_quan_huyen", resourceCulture);
            }
        }
        
        internal static string chon_quoc_gia {
            get {
                return ResourceManager.GetString("chon_quoc_gia", resourceCulture);
            }
        }
        
        internal static string chon_tinh_thanh {
            get {
                return ResourceManager.GetString("chon_tinh_thanh", resourceCulture);
            }
        }
        
        internal static string dia_chi {
            get {
                return ResourceManager.GetString("dia_chi", resourceCulture);
            }
        }
        
        internal static string gioi_tinh {
            get {
                return ResourceManager.GetString("gioi_tinh", resourceCulture);
            }
        }
        
        internal static string nhap_so_nha_duong_phuong {
            get {
                return ResourceManager.GetString("nhap_so_nha_duong_phuong", resourceCulture);
            }
        }
        
        internal static string noti_vui_long_nhap_so_nha_duong_phuong {
            get {
                return ResourceManager.GetString("noti_vui_long_nhap_so_nha_duong_phuong", resourceCulture);
            }
        }
        
        internal static string quan_huyen {
            get {
                return ResourceManager.GetString("quan_huyen", resourceCulture);
            }
        }
        
        internal static string quoc_gia {
            get {
                return ResourceManager.GetString("quoc_gia", resourceCulture);
            }
        }
        
        internal static string so_nha_duong_phuong {
            get {
                return ResourceManager.GetString("so_nha_duong_phuong", resourceCulture);
            }
        }
        
        internal static string tinh_thanh {
            get {
                return ResourceManager.GetString("tinh_thanh", resourceCulture);
            }
        }
        
        internal static string mat_khau_cu {
            get {
                return ResourceManager.GetString("mat_khau_cu", resourceCulture);
            }
        }
        
        internal static string mat_khau_moi {
            get {
                return ResourceManager.GetString("mat_khau_moi", resourceCulture);
            }
        }
        
        internal static string nhap_mat_khau_cu {
            get {
                return ResourceManager.GetString("nhap_mat_khau_cu", resourceCulture);
            }
        }
        
        internal static string nhap_mat_khau_moi {
            get {
                return ResourceManager.GetString("nhap_mat_khau_moi", resourceCulture);
            }
        }
        
        internal static string nhap_xac_nhan_mat_khau_moi {
            get {
                return ResourceManager.GetString("nhap_xac_nhan_mat_khau_moi", resourceCulture);
            }
        }
        
        internal static string noti_ban_dang_su_dung_mat_khau_cu_vui_long_nhap_lai {
            get {
                return ResourceManager.GetString("noti_ban_dang_su_dung_mat_khau_cu_vui_long_nhap_lai", resourceCulture);
            }
        }
        
        internal static string noti_doi_mat_khau_that_bai {
            get {
                return ResourceManager.GetString("noti_doi_mat_khau_that_bai", resourceCulture);
            }
        }
        
        internal static string noti_mat_khau_cu_khong_dung {
            get {
                return ResourceManager.GetString("noti_mat_khau_cu_khong_dung", resourceCulture);
            }
        }
        
        internal static string noti_mat_khau_khong_duoc_chua_ky_tu_khoan_trang {
            get {
                return ResourceManager.GetString("noti_mat_khau_khong_duoc_chua_ky_tu_khoan_trang", resourceCulture);
            }
        }
        
        internal static string noti_vui_long_nhap_mat_khau_cu {
            get {
                return ResourceManager.GetString("noti_vui_long_nhap_mat_khau_cu", resourceCulture);
            }
        }
        
        internal static string noti_vui_long_nhap_mat_khau_moi {
            get {
                return ResourceManager.GetString("noti_vui_long_nhap_mat_khau_moi", resourceCulture);
            }
        }
        
        internal static string noti_vui_long_nhap_xac_nhan_mat_khau_moi {
            get {
                return ResourceManager.GetString("noti_vui_long_nhap_xac_nhan_mat_khau_moi", resourceCulture);
            }
        }
        
        internal static string noti_xac_nhan_mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("noti_xac_nhan_mat_khau_khong_dung", resourceCulture);
            }
        }
        
        internal static string title_doi_mat_khau {
            get {
                return ResourceManager.GetString("title_doi_mat_khau", resourceCulture);
            }
        }
        
        internal static string mat_khau_khong_dung {
            get {
                return ResourceManager.GetString("mat_khau_khong_dung", resourceCulture);
            }
        }
        
        internal static string giu_cho_trang_chu {
            get {
                return ResourceManager.GetString("giu_cho_trang_chu", resourceCulture);
            }
        }
        
        internal static string dat_coc_trang_chu {
            get {
                return ResourceManager.GetString("dat_coc_trang_chu", resourceCulture);
            }
        }
        
        internal static string hop_dong_trang_chu {
            get {
                return ResourceManager.GetString("hop_dong_trang_chu", resourceCulture);
            }
        }
        
        internal static string da_ban_trang_chu {
            get {
                return ResourceManager.GetString("da_ban_trang_chu", resourceCulture);
            }
        }
        
        internal static string loyalty {
            get {
                return ResourceManager.GetString("loyalty", resourceCulture);
            }
        }
        
        internal static string xac_nhan_mat_khau_moi {
            get {
                return ResourceManager.GetString("xac_nhan_mat_khau_moi", resourceCulture);
            }
        }
    }
}
